### ISSUE TITLE
Predicting on a folder of images doesn't work

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/kiosk-frontend#119]
I submitted a folder with two images inside. However, the returned prediction was just a single prediction corresponding to the second image in the folder.

**Comment by willgraf** [comment]
Only single file uploads are supported.

When using the file browser, selecting a folder is disallowed. However, when using the "drag and drop" dropzone functionality, it allows the user to "upload" a folder though it only selects the first file in the folder.

**Comment by willgraf** [comment]
Looks like we can just check if there were more than a single dropped file, and throw an error.

<img width="441" alt="Screen Shot 2020-07-23 at 2 18 27 PM" src="https://user-images.githubusercontent.com/7930703/88339798-87740880-ccef-11ea-939a-58c61df59c86.png">

Any thoughts on the error message @ngreenwald ?

**Comment by ngreenwald** [comment]
Yeah I think that looks great!
