### ISSUE TITLE
Add documentation for data formats

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/kiosk-frontend#122]
Would be nice to add information about the file/folder structure the different models expect. For example:
- specifying that multiple files should be zipped together
- specifying that segmentation and tracking take in single-channel 2D data
- specifying that multiplex takes in multichannel 2D data, with nuclear channel first and membrane channel second
- specifying that multiplex only accepts multichannel tifs with channels last, which is not the typical image format

**Comment by willgraf** [comment]
While some information is added in #128, it would be best to include the required information on the /predict page to better inform users when they are about to select a model.

From #128:

> It would be nice if there was some way to have the description of required input data for each model more easily visible from the model dropdown section on the website.
> 
> Right now, if someone goes to deepcell.org/predict, it wouldn't be obvious how to find out what the requirements are for each model, or even what the different models do.
