### ISSUE TITLE
Add contact us/help/issues link

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/kiosk-frontend#137]
We should have somewhere on deepcell.org to direct people if they run into issues. This could be a web form, an email, or a link to an issues page.

**Comment by willgraf** [comment]
The FAQ does direct users to an issues page in the "Where can I get help?" section. Is that sufficient?

**Comment by ngreenwald** [comment]
Yeah, once we do the complete overhaul of the FAQ/About section we can rethink it
