### ISSUE TITLE
Add scale functionality to frontend

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/kiosk-frontend#165]
We previously had rescaling incorporated into the frontend as part of the scale-detection module. The user had a checkbox for "rescale automatically" or "manually rescale." If the manual option was selected, then a textbox appeared that allowed the user to enter a scale factor. 

This UI was a bit confusing. It wasn't clear what automatic scale detection was, or what the units of the manual rescaling were, whether it was necessary or not, etc. 

However, given that people will be providing data outside of the expected scale range, having this functionality in place on the website would be quite useful. In particular, I think having a multiplicative factor makes the most sense. We can tell users that the model expects data of xx resolution, and if they would like to supply data of a smaller or larger resolution, they can indicate the requested scale factor to align their data with the expectations of the model.

**Comment by willgraf** [comment]
Enabling scaling is very easy to do, but it sounds like we need to refactor the UI for the ScaleForm. Here's a screenshot of the old ScaleForm:
<img width="453" alt="Screen Shot 2021-08-06 at 11 58 59 AM" src="https://user-images.githubusercontent.com/7930703/128559054-08b576d8-a7dc-4e98-ba06-2e83c0741fb9.png">

Can you please help me draft what we would like it to look like instead?
- what does the prompt say?
- do we allow users to input the scale factor or use a dropdown (10x, 20x, 40x, etc)?
- what is the data actually trained on?

**Comment by ngreenwald** [comment]
What do you/@MekWarrior think would be more intuitive? A dropdown saying "select the resolution your data was acquired at", with options for 10X, 20X (default), 40X, 60X? Or a dropdown saying "select how your data will be rescaled", with options for 0.5X, 1X (default), 1.5X, 2X, etc.

**Comment by willgraf** [comment]
> A dropdown saying "select the resolution your data was acquired at", with options for 10X, 20X (default), 40X, 60X

This sounds pretty easy to me, but are we going to need to keep adding new NX resolutions to the dropdown? Or is the set of 4 you mentioned comprehensive?

If we expect there to be many more options, I think they should be able to input a value - though the correct multiplier value may not be very intuitive either.

**Comment by ngreenwald** [comment]
I don't think we'll need more options, we can say pick the closest one or something to that effect.

**Comment by willgraf** [comment]
Here's a couple mockups that feature both zoom and mpp values:

<img width="465" alt="Screen Shot 2021-08-12 at 1 41 20 PM" src="https://user-images.githubusercontent.com/7930703/129266831-d482ee60-79db-42ce-86e6-3978e1705678.png">

<img width="495" alt="Screen Shot 2021-08-12 at 1 42 07 PM" src="https://user-images.githubusercontent.com/7930703/129266878-805188fc-30c1-4692-8469-b0b3b8630dff.png">

Anything you like/don't like/want to see changed?
