### ISSUE TITLE
sorting of models

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-frontend#46]
If models in the model dropdown on the `/predict` page were sorted, it would facilitate testing via a headless browser, i.e., via Selenium. It wouldn't be sufficient, though, to ensure that the browser encountered the same page every time. For that, we would also need something like a dedicated "testing" bucket, so that we know we're always seeing the same list of models in the same order.

**Comment by willgraf** [comment]
Fixed by #47
